In [2]:
import pandas as pd
import numpy as np

In [4]:
# Create a DataFrame with one column "Numbers" and values from 1 - 10
df = pd.DataFrame(list(range(1,11)), columns=["Numbers"])

In [7]:
df["new_col"]=df["Numbers"].apply(lambda x: "Even" if x%2==0 else "Odd")

In [9]:
# df.loc[ condition, new_col_name] = expression
df.loc[df["Numbers"]%2==0 , "EvenOdd"] = "Even"
df.loc[df["Numbers"]%2 !=0 , "EvenOdd"] = "Odd"
# one statemnt

In [13]:
df["NewEO"] = np.where(df["Numbers"]%2==0 , "Even", "Odd")

In [16]:
# help(np.where)

In [17]:
store1 = pd.DataFrame()
store1["Product1"] = ["Mac","IPad","IPhone","IWatch","TV"]
store1["Price1"] = [2000, 900, 800, 500, 400]

In [18]:
store2 = pd.DataFrame()
store2["Product2"] = ["Mac","IPad","IPhone","IWatch","TV"]
store2["Price2"] = [1900, 900, 750, 500, 350]

In [21]:
# use np.where and check if Price1 is the Same as Price 
# if yes return True or False save results in 
# store1 df under name "Same"
store1["Same"] = np.where(store1["Price1"]==store2["Price2"], True, False)

In [23]:
store1
# if Price1 is greater than Price2 get difference between the prices
# otherwise return 0 ---> "Diff"
store1["Diff"] = np.where(store1["Price1"] > store2["Price2"], store1["Price1"] - store2["Price2"], 0)
# if Col Same False reduce Price1 by 20% if True reduce by 10%
# save under "Sale"

  Product1  Price1   Same  Diff
0      Mac    2000  False   100
1     IPad     900   True     0
2   IPhone     800  False    50
3   IWatch     500   True     0
4       TV     400  False    50

In [26]:
store1["Sale"] = np.where(store1["Same"], 0.9*store1["Price1"],0.8*store1["Price1"])

In [30]:
store1["NewSale"] = store1.apply(lambda d : 0.9*d["Price1"] if d["Same"] else 0.8*d["Price1"] ,axis=1)

In [31]:
store1
# redo this exercise with loc

  Product1  Price1   Same  Diff    Sale  NewSale
0      Mac    2000  False   100  1600.0   1600.0
1     IPad     900   True     0   810.0    810.0
2   IPhone     800  False    50   640.0    640.0
3   IWatch     500   True     0   450.0    450.0
4       TV     400  False    50   320.0    320.0

In [32]:
store1.loc[store1["Same"], "NewSale2"] = store1["Price1"]*0.9
store1.loc[store1["Same"]==False, "NewSale2"] = store1["Price1"]*0.8
store1

  Product1  Price1   Same  Diff    Sale  NewSale  NewSale2
0      Mac    2000  False   100  1600.0   1600.0    1600.0
1     IPad     900   True     0   810.0    810.0     810.0
2   IPhone     800  False    50   640.0    640.0     640.0
3   IWatch     500   True     0   450.0    450.0     450.0
4       TV     400  False    50   320.0    320.0     320.0

In [34]:
store = store1[["Product1","Price1","Same"]][::-1].copy()

In [39]:
rows1 = pd.concat([store,store2], axis=0, keys=["x","y"])

In [40]:
rows2 = pd.concat([store,store2], axis=0)
rows2.reset_index(drop=True, inplace=True)

In [45]:
store.reset_index(drop=True, inplace=True)

In [46]:
pd.concat([store,store2], axis=1)

  Product1  Price1   Same Product2  Price2
0       TV     400  False      Mac    1900
1   IWatch     500   True     IPad     900
2   IPhone     800  False   IPhone     750
3     IPad     900   True   IWatch     500
4      Mac    2000  False       TV     350

In [49]:
m = pd.merge(store, store2, left_on="Product1", right_on="Product2")
m

  Product1  Price1   Same Product2  Price2
0       TV     400  False       TV     350
1   IWatch     500   True   IWatch     500
2   IPhone     800  False   IPhone     750
3     IPad     900   True     IPad     900
4      Mac    2000  False      Mac    1900